// Generated by CoffeeScript 1.3.3
(function() {
  var SignatureCapture,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  SignatureCapture = (function() {

    function SignatureCapture(canvasID, options) {
      this.onCanvasTouchEnd = __bind(this.onCanvasTouchEnd, this);

      this.onCanvasTouchMove = __bind(this.onCanvasTouchMove, this);

      this.onCanvasTouchStart = __bind(this.onCanvasTouchStart, this);
      console.log('SignatureCapture init');
      this.canvas = document.getElementById(canvasID);
      console.log("canvas width: " + this.canvas.width + ", height: " + this.canvas.height);
      this.context = this.canvas.getContext('2d');
      this.context.strokeStyle = (options != null ? options.strokeStyle : void 0) || '#000000';
      this.context.lineWidth = (options != null ? options.lineWidth : void 0) || 1;
      this.offset = (options != null ? options.offset : void 0) || {
        left: 0,
        top: 0
      };
      this.lastMousePoint = {
        x: 0,
        y: 0
      };
      this.canvas.addEventListener('touchstart', this.onCanvasTouchStart);
    }

    SignatureCapture.prototype.onCanvasTouchStart = function(e) {
      console.log('SignatureCapture touchstart');
      document.addEventListener('touchmove', this.onCanvasTouchMove);
      document.addEventListener('touchend', this.onCanvasTouchEnd);
      this.updateMousePosition(e);
      return this.updateCanvas(e);
    };

    SignatureCapture.prototype.onCanvasTouchMove = function(e) {
      this.updateCanvas(e);
      return e.preventDefault();
    };

    SignatureCapture.prototype.onCanvasTouchEnd = function() {
      console.log('SignatureCapture touchend');
      document.removeEventListener('touchmove', this.onCanvasTouchMove);
      return document.removeEventListener('touchend', this.onCanvasTouchEnd);
    };

    SignatureCapture.prototype.updateMousePosition = function(e) {
      var target;
      target = e.touches[0];
      this.lastMousePoint.x = target.pageX - this.offset.left;
      return this.lastMousePoint.y = target.pageY - this.offset.top;
    };

    SignatureCapture.prototype.updateCanvas = function(e) {
      this.context.beginPath();
      this.context.moveTo(this.lastMousePoint.x, this.lastMousePoint.y);
      this.updateMousePosition(e);
      this.context.lineTo(this.lastMousePoint.x, this.lastMousePoint.y);
      return this.context.stroke();
    };

    SignatureCapture.prototype.toString = function() {
      var dataString, index;
      dataString = this.canvas.toDataURL('image/png');
      index = dataString.indexOf(',') + 1;
      return dataString.substring(index);
    };

    SignatureCapture.prototype.clear = function() {
      return this.context.clearRect(0, 0, parseInt(this.canvas.width), parseInt(this.canvas.height));
    };

    return SignatureCapture;

  })();

  if (this === window) {
    this.SignatureCapture = SignatureCapture;
  } else {
    if (typeof module !== "undefined" && module !== null) {
      module.exports = SignatureCapture;
    }
  }

}).call(this);
